version: '3'

services:
  postgres-postgis-pgrouting:
    build:
      context: .
      dockerfile: Dockerfile
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: pass
      POSTGRES_DB: tarea2
    ports:
      - "5432:5432"
